### ISSUE TITLE
Account deletion not possible when a user takes a polyphenol FFQ

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-private-api#492] opened 2022-11-23 16:11 UTC
From the logs. It appears that the polyphenol FFQ table may not be cleaned up correctly prior to account delete.

```
[2022-11-22 13:06:38 -0800] [7400] [ERROR] Exception on /api/accounts/b499417a-0840-44da-b269-d243f6eb02ae [DELETE]
Traceback (most recent call last):
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/security.py", line 327, in wrapper
    return function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/response.py", line 103, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/Users/api_user/microsetta-private-api-2022.11.2/microsetta_private_api/admin/admin_impl.py", line 849, in delete_account
    acct_repo.delete_account(account_id)
  File "/Users/api_user/microsetta-private-api-2022.11.2/microsetta_private_api/repo/account_repo.py", line 207, in delete_account
    cur.execute("DELETE FROM account WHERE account.id = %s",
psycopg2.errors.ForeignKeyViolation: update or delete on table "account" violates foreign key constraint "fk_polyphenol_ffq_registry_account" on table "polyphenol_ffq_registry"
DETAIL:  Key (id)=(b499417a-0840-44da-b269-d243f6eb02ae) is still referenced from table "polyphenol_ffq_registry".
```

**Comment by cassidysymons** [comment] 2022-11-29 07:03
I just looked into this, and the issue is reproducible with the following sequence of events:
1) Create an account
2) Create a human source
3) Take a remote survey with that source (any remote survey, not just the Polyphenol FFQ)
4) Delete the source
5) Attempt to delete the account

The reason this occurs is that the delete_[remote_survey]() functions are called when an admin attempts to delete an account, but are _not_ called when a participant deletes their own source, leaving orphan entries in those tables. Then, when an admin attempts to delete an account, the account_has_external flag is dependent on finding a remote survey attached to a source - with no sources, it's impossible to set the account_has_external flag to true.

We could modify the functionality when a source is deleted to also remove the remote survey entries (although that's contrary to the stated intent in the comments), but that still leaves the issue of existing accounts that have taken a remote survey, then deleted the corresponding source (we know the number of accounts matching that criteria to be non-zero).

Rather than modify the behavior of the get_[remote_survey]_id_if_exists() functions to make source_id an option parameter and risk unintended behavior elsewhere in the system, adding an account_has_remote_surveys() function to SurveyTemplateRepo seems like the safest and most expedient path.

**Comment by wasade** [comment] 2022-11-29 16:18
We scrub rather than delete sources if they have local surveys, what about extending that to remote surveys as well?

**Comment by cassidysymons** [comment] 2022-11-29 16:42
We don't scrub sources if they have local surveys - all of the surveys are deleted, then the source is deleted. I'd be fine moving to a scrub model rather than delete (although I don't think that's a top priority), but it doesn't solve the core problem that led to this issue, which is there already exists an account whose source was deleted and has remote survey registry entries attached.

I think the approach I have in [this PR](_create_dummy_acct_from_t) mostly makes sense, aside from the cleanup aspect in test_api.py. To accurately test the changes, we need to create an account, create a source, take a remote survey, delete the source, then scrub the account. I could modify the cleanup code to intelligently scrub accounts as appropriate, rather than just delete, but since the account IDs are hard-coded, the accounts need to be truly deleted for the tests to work more than once.

A potential workaround would be to add in a hack to properly delete the account with the orphaned account. I don't love the idea of using a hacky workaround in tests, but I also don't love the idea of re-writing a significant amount of the testing code to use dynamic account IDs rather than static ones.

**Closed** 2024-01-25 22:04 UTC
