### ISSUE TITLE
Hook up consent form

### ISSUE THREAD

**Issue by dhakim87** [biocore/microsetta-private-api#44] opened 2020-01-10 00:37 UTC
Hook up the consent form from /consent to successfully create a new human source.

**Comment by AmandaBirmingham** [comment] 2020-01-10 22:25
@dhakim87  I think this is a duplicate of #27 ? Or am I missing something?

**Comment by dhakim87** [comment] 2020-01-10 22:37
Yup!  Closing this one and assigning #27 to milestone 1.  
Duplicate of #27

**Comment by dhakim87** [comment] 2020-01-10 22:38
Duplicate of #27

**Comment by wasade** [comment] 2020-01-13 08:30
If this is a duplicate, should it be closed?

**Closed** 2020-01-13 08:30 UTC
